services:
  catalouge:
    build:
      dockerfile: catalouge.Dockerfile
    image: catalouge:1.0.0
    container_name: catalouge
    depends_on:
      - mongodb
  mongodb:
    build: 
      dockerfile: mongodb.Dockerfile
    image: mongodb:1.0.0
    container_name: mongodb
  frontend:
    build: 
      dockerfile: frontend.Dockerfile
    image: frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalouge